import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'
import './globals.css'


const manrope = Manrope({ subsets: ['latin'] })

export const metadata: Metadata = {
  icons:"/favicon.png",
  title: 'MainPlume',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        {children}</body>
    </html>
  )
}
